/// Each RetroArch core's `library_name`: the `corename` in its `.info` file
/// in libretro/libretro-core-info (5a74858, 2026-09-15). With "Sort Saves /
/// States into Folders by Core" on, RetroArch names a core's save and state
/// folders after it, e.g. `saves/Beetle PSX HW/`.
///
/// Covers every core in kRetroArchCores that has an .info file, plus other
/// cores Freegosy recognises in retroarch.cfg.
const Map<String, String> kRetroArchCoreLibraryNames = {
  'mgba_libretro':                      'mGBA',
  'gambatte_libretro':                  'Gambatte',
  'sameboy_libretro':                   'SameBoy',
  'gearboy_libretro':                   'Gearboy',
  'tgbdual_libretro':                   'TGB Dual',
  'mesen_libretro':                     'Mesen',
  'fceumm_libretro':                    'FCEUmm',
  'nestopia_libretro':                  'Nestopia',
  'quicknes_libretro':                  'QuickNES',
  'fixnes_libretro':                    'fixNES',
  'snes9x_libretro':                    'Snes9x',
  'bsnes_libretro':                     'bsnes',
  'bsnes2014_accuracy_libretro':        'bsnes 2014 Accuracy',
  'bsnes2014_balanced_libretro':        'bsnes 2014 Balanced',
  'bsnes2014_performance_libretro':     'bsnes 2014 Performance',
  'bsnes_hd_beta_libretro':             'bsnes-hd beta',
  'bsnes_mercury_accuracy_libretro':    'bsnes-mercury Accuracy',
  'bsnes_mercury_balanced_libretro':    'bsnes-mercury Balanced',
  'bsnes_mercury_performance_libretro': 'bsnes-mercury Performance',
  'bsnes-jg_libretro':                  'bsnes-jg',
  'bsnes_cplusplus98_libretro':         'bsnes C++98 (v085)',
  'mednafen_snes_libretro':             'Beetle bsnes',
  'mednafen_supafaust_libretro':        'Beetle Supafaust',
  'snes9x2002_libretro':                'Snes9x 2002',
  'snes9x2005_libretro':                'Snes9x 2005',
  'snes9x2005_plus_libretro':           'Snes9x 2005 Plus',
  'snes9x2010_libretro':                'Snes9x 2010',
  'mupen64plus_next_libretro':          'Mupen64Plus-Next',
  'parallel_n64_libretro':              'ParaLLEl N64',
  'melonds_libretro':                   'melonDS',
  'melondsds_libretro':                 'melonDS DS',
  'desmume2015_libretro':               'DeSmuME 2015',
  'desmume_libretro':                   'DeSmuME',
  'meteor_libretro':                    'Meteor',
  'azahar_libretro':                    'Azahar',
  'citra_libretro':                     'Citra',
  'citra2018_libretro':                 'Citra 2018',
  'panda3ds_libretro':                  'Panda3DS',
  'mednafen_vb_libretro':               'Beetle VB',
  'vecx_libretro':                      'vecx',
  'lowresnx_libretro':                  'lowresnx',
  'tic80_libretro':                     'TIC-80',
  'wasm4_libretro':                     'WASM-4',
  'retro8_libretro':                    'Retro8',
  'genesis_plus_gx_libretro':           'Genesis Plus GX',
  'genesis_plus_gx_wide_libretro':      'Genesis Plus GX Wide',
  'picodrive_libretro':                 'PicoDrive',
  'gearsystem_libretro':                'Gearsystem',
  'smsplus_libretro':                   'SMS Plus GX',
  'blastem_libretro':                   'BlastEm',
  'flycast_libretro':                   'Flycast',
  'kronos_libretro':                    'Kronos',
  'yabasanshiro_libretro':              'YabaSanshiro',
  'yabause_libretro':                   'Yabause',
  'mednafen_saturn_libretro':           'Beetle Saturn',
  'geolith_libretro':                   'Geolith',
  'mednafen_psx_hw_libretro':           'Beetle PSX HW',
  'pcsx_rearmed_libretro':              'PCSX-ReARMed',
  'mednafen_psx_libretro':              'Beetle PSX',
  'swanstation_libretro':               'SwanStation',
  'ppsspp_libretro':                    'PPSSPP',
  'pcsx2_libretro':                     'LRPS2',
  'mednafen_pce_fast_libretro':         'Beetle PCE Fast',
  'mednafen_pce_libretro':              'Beetle PCE',
  'mednafen_supergrafx_libretro':       'Beetle SuperGrafx',
  'mednafen_pcfx_libretro':             'Beetle PC-FX',
  'neocd_libretro':                     'NeoCD',
  'stella_libretro':                    'Stella',
  'stella2014_libretro':                'Stella 2014',
  'stella2023_libretro':                'Stella 2023',
  'prosystem_libretro':                 'ProSystem',
  'atari800_libretro':                  'Atari800',
  'a5200_libretro':                     'a5200',
  'handy_libretro':                     'Handy',
  'mednafen_lynx_libretro':             'Beetle Lynx',
  'gearlynx_libretro':                  'Gearlynx',
  'mednafen_wswan_libretro':            'Beetle WonderSwan',
  'mednafen_ngp_libretro':              'Beetle NeoPop',
  'pokemini_libretro':                  'PokeMini',
  'gw_libretro':                        'GW',
  'fbneo_libretro':                     'FinalBurn Neo',
  'fbalpha2012_libretro':               'FB Alpha 2012',
  'fbalpha2012_cps1_libretro':          'FB Alpha 2012 CPS-1',
  'fbalpha2012_cps2_libretro':          'FB Alpha 2012 CPS-2',
  'fbalpha2012_cps3_libretro':          'FB Alpha 2012 CPS-3',
  'fbalpha2012_neogeo_libretro':        'FB Alpha 2012 Neo Geo',
  'mame2000_libretro':                  'MAME 2000 (0.37b5)',
  'mame2003_libretro':                  'MAME 2003 (0.78)',
  'mame2003_plus_libretro':             'MAME 2003-Plus',
  'mame2003_midway_libretro':           'MAME 2003 Midway (0.78)',
  'mame2010_libretro':                  'MAME 2010 (0.139)',
  'mame_libretro':                      'MAME',
  'hbmame_libretro':                    'HBMAME (Git)',
  'same_cdi_libretro':                  'SAME CDi (Git)',
  'dosbox_pure_libretro':               'DOSBox-pure',
  'dosbox_core_libretro':               'DOSBox-core',
  'dosbox_svn_libretro':                'DOSBox-SVN',
  'bluemsx_libretro':                   'blueMSX',
  'fmsx_libretro':                      'fMSX',
  'fuse_libretro':                      'Fuse',
  'cap32_libretro':                     'Caprice32',
  'hatari_libretro':                    'hatari',
  'vice_x64_libretro':                  'VICE x64',
  'vice_x64sc_libretro':                'VICE x64sc',
  'vice_xscpu64_libretro':              'VICE xscpu64',
  'vice_x128_libretro':                 'VICE x128',
  'vice_xvic_libretro':                 'VICE xvic',
  'vice_xpet_libretro':                 'VICE xpet',
  'vice_xplus4_libretro':               'VICE xplus4',
  'vice_xcbm2_libretro':                'VICE xcbm2',
  'vice_xcbm5x0_libretro':              'VICE xcbm5x0',
  'puae_libretro':                      'PUAE',
  'puae2021_libretro':                  'PUAE 2021',
  'px68k_libretro':                     'PX68k',
  'np2kai_libretro':                    'Neko Project II Kai',
  'quasi88_libretro':                   'QUASI88',
  'x1_libretro':                        'x1',
  'applewin_libretro':                  'applewin',
  'frodo_libretro':                     'Frodo',
  'ep128emu_core_libretro':             'ep128emu-core',
  'o2em_libretro':                      'O2EM',
  'bbkemu_libretro':                    'BBKEmu',
  'm2000_libretro':                     'M2000',
  'mojozork_libretro':                  'mojozork',
  'theodore_libretro':                  'theodore',
  'freechaf_libretro':                  'FreeChaF',
  'freeintv_libretro':                  'FreeIntv',
  'virtualjaguar_libretro':             'Virtual Jaguar',
  'opera_libretro':                     'Opera',
  'crocods_libretro':                   'CrocoDS',
  'prboom_libretro':                    'PrBoom',
  'ecwolf_libretro':                    'ECWolf',
  'nxengine_libretro':                  'NXEngine',
  'tyrquake_libretro':                  'TyrQuake',
  'openlara_libretro':                  'OpenLara',
  'vitaquake2_libretro':                'vitaQuake 2',
  'vitaquake2-rogue_libretro':          'vitaQuake 2 [Rogue]',
  'vitaquake2-xatrix_libretro':         'vitaQuake 2 [Xatrix]',
  'vitaquake2-zaero_libretro':          'vitaQuake 2 [Zaero]',
  'vitaquake3_libretro':                'vitaQuake 3',
  'reminiscence_libretro':              'REminiscence',
  'doukutsu_rs_libretro':               'doukutsu-rs',
  'craft_libretro':                     'Craft',
  'chailove_libretro':                  'ChaiLove',
  'mrboom_libretro':                    'Mr.Boom',
  'boom3_libretro':                     'boom3',
  'gong_libretro':                      'Gong',
  'jumpnbump_libretro':                 'jumpnbump',
  'xrick_libretro':                     'XRick',
  'dice_libretro':                      'DICE',
  'dinothawr_libretro':                 'Dinothawr',
  'dirksimple_libretro':                'DirkSimple',
  '2048_libretro':                      '2048',
  'b2_libretro':                        'b2',
  'cdi2015_libretro':                   'Philips CDi 2015',
  'doublecherrygb_libretro':            'DoubleCherryGB',
  'holani_libretro':                    'Holani',
  'irogb_libretro':                     'IroGB',
  'jollycv_libretro':                   'JollyCV',
  'lutro_libretro':                     'Lutro',
  'mcsoftserve_libretro':               'mcsoftserve',
  'mu_libretro':                        'Mu',
  'native32emu_libretro':               'native32emu',
  'nekop2_libretro':                    'Neko Project II',
  'noods_libretro':                     'NooDS',
  'numero_libretro':                    'Numero',
  'nuance_libretro':                    'Nuance',
  'oberon_libretro':                    'Oberon',
  'pd777_libretro':                     'PD777',
  'play_libretro':                      'Play!',
  'pocketcdg_libretro':                 'PocketCDG',
  'romcleaner_libretro':                'romcleaner',
  'sameduck_libretro':                  'SameDuck',
  'skyemu_libretro':                    'SkyEmu',
  'squirreljme_libretro':               'SquirrelJME',
  'superbroswar_libretro':              'superbroswar',
  'tamalibretro_libretro':              'TamaLIBretro',
  'thepowdertoy_libretro':              'ThePowderToy',
  'tia_libretro':                       'Tia',
  'uzem_libretro':                      'uzem',
  'uw8_libretro':                       'MicroW8',
  'vaporspec_libretro':                 'VaporSpec',
  'vbam_libretro':                      'VBA-M',
  'vba_next_libretro':                  'VBA Next',
  'vemulator_libretro':                 'VeMUlator',
  'vircon32_libretro':                  'Vircon32',
  'virtualxt_libretro':                 'virtualxt',
  '81_libretro':                        '81',
  'bk_libretro':                        'bk',
  'galaksija_libretro':                 'galaksija',
  'gpsp_libretro':                      'gpSP',
  'duckstation_libretro':               'DuckStation',
};
